# Generated by Django 5.1.1 on 2025-11-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="file_path",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="thumbnail_path",
        ),
        migrations.AddField(
            model_name="photo",
            name="aperture",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="photo",
            name="camera_make",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="photo",
            name="camera_model",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="photo",
            name="file",
            field=models.FileField(
                max_length=512, null=True, upload_to="photos/originals/"
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="focal_length",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="photo",
            name="iso",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="lens_model",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="photo",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="shutter_speed",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="photo",
            name="thumbnail",
            field=models.ImageField(
                blank=True, max_length=512, null=True, upload_to="photos/thumbnails/"
            ),
        ),
    ]
